fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: ambroise.jerome.formation@gmail.com
    sender_name: ambroise.jerome.formation@gmail.com