#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\ProjectController::home
##les routes de  FOSUserBundles
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"